spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/commerce
    username: commerce
    password: commerce
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  management:
    endpoints:
      web:
        exposure:
          include: health

jwt:
  secret: my-super-long-secret-key-for-event-driven-commerce-platform-jwt-authentication-2026