
spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: commerce
    password: commerce
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  kafka:
    bootstrap-servers: localhost:9092


server:
  port: 8084
